---
title: "Review"
date: "Last updated on `r Sys.Date()`"
author: "Mauro Lepore (maurolepore@gmail.com)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

See [review](https://github.com/maurolepore/pacta/blob/mauro-review/.buildignore/mauro-review.md).

### General suggestions

* Automate the development process with the [usethis](https://usethis.r-lib.org/) packages. The first version of the [R packages](http://r-pkgs.had.co.nz/) book was published before usethis existed. The [work-in-progress version of that book](https://r-pkgs.org) uses usethis. See also the [Tidyverse design principles](https://principles.tidyverse.org/).

* Prefer this style guide: https://style.tidyverse.org/. For example, avoid `.` in object names::

> Base R uses dots in function names (contrib.url()) and class names (data.frame), but it’s better to reserve dots exclusively for the S3 object system. In S3, methods are given the name function.class; if you also use . in function and class names, you end up with confusing methods like as.data.frame.data.frame().
--https://style.tidyverse.org/syntax.html#object-names

* On TravisCI, check with multiple versions of R (at least devel, release, and oldrel). 

* Write documentation with users in mind, not developers:
    * Usually there are more users than developers.
    * Development details (e.g. use devtools and roxygen2) should be irrelevant to using a package.
    * Developers should be familiar with standard development practices. If needed, details should be provided in dedicated developer-facing documentation.

* Consider using the standard README  template, as provided via `usethis::use_readme_rmd()`.

* Consider developing a developer-facing package to provide templates ([example](https://forestgeo.github.io/fgeo.template/)).

* Enable rmarkdown syntax in the documentation via the [roxygen2md](https://github.com/r-lib/roxygen2md) package.

* Build websites for all user-facing packages ([pkdown](https://pkgdown.r-lib.org/)) ([example](https://forestgeo.github.io/fgeo/)).

* Consider using checklists to standardize processes that aren't easy to capture in code:
    * [Checklist to build R packages](https://fgeo.netlify.com/2018/03/28/2018-03-28-building-infrastructure-for-r-packages-with-usethis/)
    * [Checklist to release a package to CRAN](https://github.com/forestgeo/learn/issues/212)

* Make it easy to find useful resources ([example](https://github.com/forestgeo/learn)).

* Think of a common prefix for all packages of the organization, which may become a meta-package (ala tidyverse) ([example](https://forestgeo.github.io/fgeo/)). (Unfortunately 2dii is an invalid package name, but twodii is valid).

* Develop APIs and data structures consistently across packages.
* If you need a custom data structure, define it as an S3 class (if possible) as soon as possible. This simplifies downstream checks for data quality.

* For tests and examples, create a package containing tiny versions of the typical dataset ([example](https://forestgeo.github.io/fgeo.x/)). This makes it easy to access data from mulitple package.

* Provide examples for every function.

### Specific suggestions

For specific suggestions, see each commit message.
